FROM kasmweb/core-ubuntu-jammy:1.16.0

USER root
RUN apt-get update && apt-get install -y \
    python3-pip \
    python3-dev \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install --upgrade pip
RUN pip3 install open-interpreter

USER 1000:1000