"""deleted image types

Revision ID: 09d6e3936dbb
Revises: eede75c44748
Create Date: 2026-02-17 12:00:47.975025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09d6e3936dbb'
down_revision: Union[str, Sequence[str], None] = 'eede75c44748'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_images', 'image_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_images', sa.Column('image_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
