"""deleted image-task relation

Revision ID: 49b9d15ddf6c
Revises: 09d6e3936dbb
Create Date: 2026-02-17 12:57:57.461911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49b9d15ddf6c'
down_revision: Union[str, Sequence[str], None] = '09d6e3936dbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('task_images_task_id_fkey'), 'task_images', type_='foreignkey')
    op.drop_column('task_images', 'task_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_images', sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('task_images_task_id_fkey'), 'task_images', 'tasks', ['task_id'], ['id'])
    # ### end Alembic commands ###
