"""Added user-workers relations, task-image table

Revision ID: 58732e8c17bc
Revises: f5901b4036d7
Create Date: 2026-02-13 18:52:37.169148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58732e8c17bc'
down_revision: Union[str, Sequence[str], None] = 'f5901b4036d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('image_type', sa.String(), nullable=False),
    sa.Column('s3_url', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('workers', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'workers', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workers', type_='foreignkey')
    op.drop_column('workers', 'user_id')
    op.drop_table('task_images')
    # ### end Alembic commands ###
