"""add worker_id to image model

Revision ID: f2763ad2110f
Revises: 49b9d15ddf6c
Create Date: 2026-02-17 13:14:31.902954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2763ad2110f'
down_revision: Union[str, Sequence[str], None] = '49b9d15ddf6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_images', sa.Column('worker_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'task_images', 'workers', ['worker_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task_images', type_='foreignkey')
    op.drop_column('task_images', 'worker_id')
    # ### end Alembic commands ###
